In [1]:
pip install numpy

In [2]:
import numpy


In [3]:
import numpy as np

In [4]:
np.__version__

'1.23.5'

In [5]:
a=np.array([[[1,2,3,4,5,6,7,8]]])
a

array([[[1, 2, 3, 4, 5, 6, 7, 8]]])

In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
a1=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11]]])
a

<ipython-input-7-7bccd7081685>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a1=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11]]])


array([[[1, 2, 3, 4, 5, 6, 7, 8]]])

In [8]:
a1[0][2][1]

10

In [9]:
a1[0]

array([list([1, 2, 3, 4]), list([5, 6, 7, 8]), list([9, 10, 11])],
      dtype=object)

In [10]:
a1[0][2]

[9, 10, 11]

In [11]:
a1.ndim

2

In [12]:
a.ndim

3

In [13]:
suki=np.array([[1,2,3,4,5],[6,7,8,9,10]],ndmin=4)
suki

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [14]:
suki.shape

(1, 1, 2, 5)

In [15]:
a1.shape

(1, 3)

In [16]:
np.typecodes

{'Character': 'c',
 'Integer': 'bhilqp',
 'UnsignedInteger': 'BHILQP',
 'Float': 'efdg',
 'Complex': 'FDG',
 'AllInteger': 'bBhHiIlLqQpP',
 'AllFloat': 'efdgFDG',
 'Datetime': 'Mm',
 'All': '?bhilqpBHILQPefdgFDGSUVOMm'}

In [17]:
suki.size

10

In [18]:
suki.itemsize

8

In [19]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [20]:
suki.dtype

dtype('int64')

In [21]:
suki.sum()

55

In [22]:
suki.mean()

5.5

In [23]:
suki.max()

10

In [24]:
suki.min()

1

In [25]:
max("SUKISHA MUTHUKRISHNAN")

'U'

In [26]:
min("sukisha muthukrishnan")

' '

In [27]:
maki=np.array([[1,2,3,4,5,6,7]],dtype=np.int8)
maki

array([[1, 2, 3, 4, 5, 6, 7]], dtype=int8)

In [28]:
ms=np.array([[1,2,3,4,5,6,7]],dtype=float)
ms

array([[1., 2., 3., 4., 5., 6., 7.]])

In [29]:
ms=np.array([[1,2,3,4,5,6,7]],dtype=str)
ms

array([['1', '2', '3', '4', '5', '6', '7']], dtype='<U1')

In [30]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros([2,6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
np.ones([5,8])

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
np.empty([3,5])

array([[4.65012611e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 1.20953760e-312],
       [1.50008929e+248, 4.31174539e-096, 9.80058441e+252,
        1.23971686e+224, 1.05249946e-153],
       [9.03292329e+271, 9.08366793e+223, 1.06244660e-153,
        3.44981369e+175, 6.32404027e-322]])

In [34]:
np.empty(7)

array([1., 2., 3., 4., 5., 6., 7.])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [37]:
np.diag([54,6,89,13,57],5)

array([[ 0,  0,  0,  0,  0, 54,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  6,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 89,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 13,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 57],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [38]:
a=np.arange(1,61)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [39]:
np.sort(suki,axis=True)

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [40]:
np.sort(suki,axis=0)

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [41]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [42]:
np.concatenate((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
np.flip([24,768,12,7,980,243])

array([243, 980,   7,  12, 768,  24])

In [44]:
a=np.unique(a,return_index=True)
a

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 3, 4]))

In [45]:
a=np.unique(a,return_counts=True)
a

(array([0, 1, 2, 3, 4, 5]), array([1, 2, 2, 2, 2, 1]))

In [46]:
c=np.arange(1,81)
s=slice(1,81,6)
s

slice(1, 81, 6)

In [47]:
print(slice(c))

slice(None, array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80]), None)


In [48]:
sl=np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
sl

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
print(sl[1:7:2])

[2 4 6]


In [50]:
print(c[s])

[ 2  8 14 20 26 32 38 44 50 56 62 68 74 80]


In [51]:
a=[34,56]
b=[38,87]
np.cross(a,b)

array(830)

In [52]:
print(numpy.rint([32.4]))

[32.]


In [53]:
a=np.array([[[1,2,3,4,5,6,7,8]]])
a

array([[[1, 2, 3, 4, 5, 6, 7, 8]]])

In [54]:
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])